// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    BrandLogo: typeof import('./src/components/images/BrandLogo.vue')['default']
    BrandType: typeof import('./src/components/images/BrandType.vue')['default']
    FormKitExample: typeof import('./src/components/FormKitExample.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ICarbonMenu: typeof import('~icons/carbon/menu')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    InfoStatus: typeof import('./src/components/InfoStatus.vue')['default']
    JobStatus: typeof import('./src/components/JobStatus.vue')['default']
    Kofi: typeof import('./src/components/Kofi.vue')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    PID: typeof import('./src/components/PID.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SdForm: typeof import('./src/components/SdForm.vue')['default']
    VIconButton: typeof import('./src/components/VIconButton.vue')['default']
  }
}
